# Generated by Django 3.0.2 on 2020-01-29 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tripadvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('phone', models.IntegerField(max_length=100)),
                ('Mail_id', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
