# Generated by Django 3.0.2 on 2020-01-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripadvisors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripadvisor',
            old_name='Mail_id',
            new_name='mail_id',
        ),
        migrations.AlterField(
            model_name='tripadvisor',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tripadvisor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d'),
        ),
    ]
