# Generated by Django 3.0.2 on 2020-01-29 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tripadvisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('ideal_season', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('minimum_days', models.IntegerField(max_length=100)),
                ('price', models.IntegerField(max_length=100)),
                ('photo_main', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tripadvisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='tripadvisors.Tripadvisor')),
            ],
        ),
    ]
