# Generated by Django 3.0.2 on 2020-01-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='minimum_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='place',
            name='price',
            field=models.IntegerField(),
        ),
    ]
